# Site settings
title: 李嵩
twitter_username: songl_ws
name: 李嵩

# Build settings
markdown: kramdown

#User specific content
#Links that will appear in the navbar
primarylinks:
 - title: GitHub
   url: https://github.com/boltomli
 - title: LinkedIn
   url: https://www.linkedin.com/in/song-li-96672079

#Any buzzword skills you want to include
skills:
 - 难题攻关
 - 技术方案
 - 流程设计

#Work experience is required
roles:
 - title: 部门经理
   start: 2015
   end: 至今
   employer: Wicresoft
   description: 管理多个小组（几十人规模团队），按客户方要求完成各个子项目。负责技术研发和审核。与客户和公司进行沟通，协调各个项目经理和主管的工作和人力等各项资源。
 - title: 开发主管
   start: 2011
   end: 2015
   employer: Wicresoft
   description: 带领十人小组，按客户方要求完成相应软件与数据开发的计划与执行。与客户及第三方进行沟通、协调资源。
 - title: 测试开发工程师
   start: 2007
   end: 2011
   employer: Wicresoft
   description: 设计、开发、执行和维护多个平台上的手动与自动测试工具。创建、执行和分析主观测试。

#List of interesting Github repo/projects to include - optional
github:
 - boltomli/Data-for-CustomVoice.AI
 - boltomli/CustomLocale
 - boltomli/Neo4j-Flask-Solutions
 - boltomli/tidy-text-mining-zh
 - boltomli/speech-api
 - boltomli/custom-voice-api
 
